### ISSUE TITLE
Where windows binary?

### ISSUE THREAD

**Issue by AtmanActive** [boyter/cs#18]
Hi,

Thank you for developing this great tool.

Looking at the CLI demonstration video, it looks really useful.

However, README.md mentions binaries for windows, macos and linux in the release, but I can only see macos and linux binary releases. Seems like windows binaries are missing.

Any chance of adding windows binaries?

Thanks.

**Comment by boyter** [comment]
Ah yes. This is due to some Windows incompatibility in the code walker.

https://github.com/boyter/gocodewalker/issues/3

I have created the above to deal with that.

For the moment I recommend using WSL.

**Comment by boyter** [comment]
@AtmanActive new windows build should be on the downloads for you.

**Comment by AtmanActive** [comment]
Thank you for the quick fix.

**Comment by boyter** [comment]
@AtmanActive thanks for reporting it. It was in the back of my mind and somehow I forgot about it.
