### ISSUE TITLE
Consider `go install` support

### ISSUE THREAD

**Issue by vearutop** [boyter/cs#19]
Currently, module name does not allow `go install github.com/boyter/cs@latest`:
```
go: downloading github.com/boyter/cs v1.0.0
go: github.com/boyter/cs@latest: github.com/boyter/cs@v1.0.0: parsing go.mod:
	module declares its path as: cs
	        but was required as: github.com/boyter/cs
```

If there are no obstacles (e.g. tricky build dependencies) to build this on a user machine, it would be convenient to be able to install the tool with `go install` one-liner.

**Comment by boyter** [comment]
Pushed a fix then to resolve the go.mod so this should work, although it would have been cached by the CDN. Should be resolved when I fix the other current windows build and push out a 1.0.1 release. Keeping this open till then.

**Comment by boyter** [comment]
@vearutop Latest is annoyingly still cached but if you specify the new version it should work (for all OS now)

`go install github.com/boyter/cs@v1.1.0`
