### ISSUE TITLE
Install appears successful, but command not found; even after Terminal restart

### ISSUE THREAD

**Issue by strangelearning** [boyter/cs#20]
```sh
❯ go install github.com/boyter/cs@v1.1.0
<empty>
❯ go version
go version go1.20.4 darwin/arm64
❯ which go
/opt/homebrew/bin/go
```

I've read through the README a couple of times and can run the Release build, but was curious why this wasn't working.

Thanks in advance for your help!

**Comment by boyter** [comment]
You probably need to add the install location to your path.

```
export PATH=$PATH:$(go env GOPATH)/bin
```

Would probably do it for you. Just add that to your dotfile and you should be good!

**Comment by strangelearning** [comment]
Thanks for the tip! I added that to my `~/.zshrc` and now can run the program, but now that it runs does not appear to be functioning as I expected.

<details><summary>Shell Contents</summary>
<p>

❯ echo $PATH
/Users/laptop/Library/pnpm:/usr/local/sbin:/Users/laptop/bin:/Users/laptop/.avm/bin:/Users/laptop/.local/share/solana/install/active_release/bin:/usr/local/opt/openssl@1.1/bin:/Users/laptop/.rbenv/shims:/Users/laptop/.rbenv/bin:/Users/laptop/Library/pnpm:/opt/homebrew/Caskroom/miniconda/base/bin:/opt/homebrew/Caskroom/miniconda/base/condabin:/usr/local/sbin:/Users/laptop/bin:/Users/laptop/.avm/bin:/Users/laptop/.local/share/solana/install/active_release/bin:/usr/local/opt/openssl@1.1/bin:/Users/laptop/.rbenv/shims:/Users/laptop/.rbenv/bin:/Users/laptop/.local/share/solana/install/active_release/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/laptop/.cargo/bin:/Users/laptop/Library/Android/sdk/emulator:/Users/laptop/Library/Android/sdk/tools:/Users/laptop/Library/Android/sdk/tools/bin:/Users/laptop/Library/Android/sdk/platform-tools:/Users/laptop/.rvm/bin:/usr/local/opt/fzf/bin:/Users/laptop/Library/Android/sdk/emulator:/Users/laptop/Library/Android/sdk/tools:/Users/laptop/Library/Android/sdk/tools/bin:/Users/laptop/Library/Android/sdk/platform-tools:/Users/laptop/.rvm/bin:/Users/laptop/go/bin
❯ ls
Applications	Library		Public
Desktop		Movies		Tiny
Development	Music		foo.txt
Documents	Parallels	go
Downloads	Pictures
❯ cat foo.txt
hello


</p>
</details> 

https://github.com/boyter/cs/assets/80677888/f69b094f-5a1d-48a8-8595-adf621699f8a

**Comment by boyter** [comment]
Good news. It is working. However it works in a similar manner to grep, in that its brute forcing the search. I suspect you are running it in a very large directory.

Run it in smaller directory and it should be fine. I have been considering adding in the ability to index to enable it to scale, but dropped that idea in favor of a v1 release. Its something I am still thinking about.
