### ISSUE TITLE
pip install support

### ISSUE THREAD

**Issue by lucasjinreal** [boyter/cs#24]
hi, if there is a python glue version could be better

**Comment by boyter** [comment]
This is a Go project and I have no plans to ever consider porting it to Python.

If you do please let me know and I will link to it via the readme.

**Comment by lucasjinreal** [comment]
@boyter thanks, how to install it conveniently on windows

**Comment by boyter** [comment]
Easiest way would be to download the binary,

https://github.com/boyter/cs/releases/tag/v1.2.0

https://github.com/boyter/cs/releases/download/v1.2.0/cs_1.2.0_Windows_x86_64.tar.gz

Thats the latest windows 64 bit version for you. Should do the trick.

**Comment by boyter** [comment]
I should add if you feel like adding a chocolatey package for it let me know and I will add it to the readme.

**Comment by lucasjinreal** [comment]
@boyter hi, I really would like chocolaty if it possible, that would be very convenient just `choco install cs and cs -v`

winnget also ok.

**Comment by boyter** [comment]
Yep. So I tend to not maintain those, simply because I am not familiar enough with it, and its a pain to do.

If someone else steps in though it will be added to the readme.
