### ISSUE TITLE
cs not returning any results

### ISSUE THREAD

**Issue by nicola-zen** [boyter/cs#3]
Hey!
I wanted to try out this project as it seems very cool. Unfortunately, I cannot seem to manage to get it working. After successful compilation, it seems like it is unable to find files.

Screencast here:
https://asciinema.org/a/7COxeFJv0SMhhcQVh09WmmcuT

Let me know if you need some additional information.

Cheers!

**Comment by boyter** [comment]
Sorry about late response. This is heavily in development so I never expected any issues.

Can you try building from your GoPath as a first step.

It looks like you might have been unlucky to have cloned when I was testing things and its likely I disabled the search while working on some stuff. Can you try pulling the latest and see how that goes for you?

**Comment by nicola-zen** [comment]
Hey boyter, no problem for the late reply.

Unfortunately now I cannot compile anymore

```
Updating 2de3088..80ade4e
Fast-forward
 README.md                                          |  12 +-
 asset/corpus/{1342-0.txt => prideandprejudice.txt} |   0
 asset/corpus/snippet/chinese_war_and_peace.txt     | 346 +++++++++++++++++++++
 check.sh                                           |  45 +++
 main.go                                            |  50 ++-
 processor/file.go                                  | 192 ++++++++++++
 processor/formatters.go                            |   4 +-
 processor/helpers.go                               |  48 ++-
 processor/helpers_test.go                          |  16 +
 processor/processor.go                             |  57 +++-
 processor/processor_test.go                        |  13 +-
 processor/ranker.go                                |  20 +-
 processor/ranker_test.go                           |  26 +-
 processor/snippet/snippet.go                       |  44 ++-
 processor/snippet/snippet_test.go                  |   4 +-
 processor/snippet/standard.go                      |  47 ++-
 processor/tui.go                                   | 158 +++++++---
 processor/workers.go                               |  60 ++--
 processor/workers_test.go                          |  62 ++--
 test-all.sh                                        |  32 --
 20 files changed, 1007 insertions(+), 229 deletions(-)
 rename asset/corpus/{1342-0.txt => prideandprejudice.txt} (100%)
 create mode 100644 asset/corpus/snippet/chinese_war_and_peace.txt
 create mode 100644 check.sh
 delete mode 100644 test-all.sh
PS C:\temp\gopath\src\cs> go build
# cs
.\main.go:18:17: undefined: "github.com/boyter/cs/processor".Version
.\main.go:20:12: undefined: "github.com/boyter/cs/processor".Version
.\main.go:25:9: undefined: "github.com/boyter/cs/processor".NewProcess
.\main.go:132:4: undefined: "github.com/boyter/cs/processor".Fuzzy
.\main.go:138:4: undefined: "github.com/boyter/cs/processor".LocationExcludePattern
.\main.go:145:4: undefined: "github.com/boyter/cs/processor".CaseSensitive
.\main.go:152:4: undefined: "github.com/boyter/cs/processor".FindRoot
PS C:\temp\gopath\src\cs> go get ./...
# cs
.\main.go:18:17: undefined: "github.com/boyter/cs/processor".Version
.\main.go:20:12: undefined: "github.com/boyter/cs/processor".Version
.\main.go:25:9: undefined: "github.com/boyter/cs/processor".NewProcess
.\main.go:132:4: undefined: "github.com/boyter/cs/processor".Fuzzy
.\main.go:138:4: undefined: "github.com/boyter/cs/processor".LocationExcludePattern
.\main.go:145:4: undefined: "github.com/boyter/cs/processor".CaseSensitive
.\main.go:152:4: undefined: "github.com/boyter/cs/processor".FindRoot
# cs/processor
processor\ranker.go:37:33: cannot use searchTerms (type [][]byte) as type []string in argument to snippet.ExtractLocations
processor\ranker.go:37:33: cannot use loc (type []byte) as type string in argument to snippet.ExtractLocations
processor\workers.go:168:50: cannot use ([]byte)(t) (type []byte) as type string in argument to snippet.ExtractLocation
processor\workers.go:168:50: cannot use content (type []byte) as type string in argument to snippet.ExtractLocation
processor\workers.go:177:58: cannot use term (type []byte) as type string in argument to snippet.ExtractLocation
processor\workers.go:177:58: cannot use content (type []byte) as type string in argument to snippet.ExtractLocation
PS C:\temp\gopath\src\cs>
```

**Comment by boyter** [comment]
Pretty sure this is due to not checking out into the GOPATH.

```
go get github.com/boyter/cs/
```

then find your GOPATH. For Windows you can find it in environment variables,

![image](https://user-images.githubusercontent.com/612151/73787329-32027880-47ef-11ea-92f1-7158762a8547.png)

whatever value is in your GOPATH (in my case C:\Users\bboyter\go ) then change to the directory of your GOPATH like so for my example

```
cd  C:\Users\bboyter\go\src\github\boyter\cs\
```

If you never changed the GOPATH it will default to `go` inside your user directory.

Then try building from there.

**Comment by nicola-zen** [comment]
Oh great! I finally managed, sorry for taking your time on something so stupid. I never worked with Go actually, and I clearly misunderstood some tutorials on how to build things.

Thanks for your help, the tool looks good so far!

**Comment by boyter** [comment]
No problem at all. Just glad it was resolved for you. I am deep in the weeds dealing with unicode support at the moment but once that is resolve it should be getting closer to actually having a release date once I sort out some of the snippet issues.

**Comment by nicola-zen** [comment]
Cool. I have some improvement ideas/additional features and I started looking into the codebase, but probably best to let you finish the MVP release first. After, I will make a couple of issues/PR.

**Comment by boyter** [comment]
Feel free to raise them now and ill factor it in to what I am doing. I might not get it done for MVP but will ensure I don't code into a corner.
