### ISSUE TITLE
Idea - Option to hide/show hidden files and directories

### ISSUE THREAD

**Issue by nicola-zen** [boyter/cs#4]
### Problem definition

Currently, `cs` looks for a match in all the files that are not ignored by `.gitignore`. This is great, but sometimes there are hidden directories that are nor gitignored, nor relevant for search.

For example, as a Python developer, I have lots of tryout projects that have a `virtualenv` in them. It is common practice in the Python world to create virtual environments in a hidden folder called `.env`. A virtual environment contains Python libraries, hence a lot of searchable code. If the project is a git repo it is likely that `.env` will be part of `.gitignore`, but this does not hold for tryouts or local test projects.

### Idea

Add a switch to `cs` to ignore/not-ignore hidden files. This can be a CLI parameter for now, and maybe later added to the TUI interface.

#### Default behavior

The options are:

- ignore hidden files by default
- ignore hidden files as option

Tools like `grep` and `ripgrep` ignore hidden files by default, and that might be the experience that most developer are used to. Still, `cs` could exibit a different behavior if explicit.

### Implementation challenges

I have the feeling that `cs` aims at being cross platform, hence a different detection mechanism has to be implemented for Windows and Linux. [Some pointers can be found here](https://socketloop.com/tutorials/golang-how-to-check-if-a-file-is-hidden). The combination of this and [build tags](https://stackoverflow.com/a/54139711) should lead to a cross platform solution.

### Notes

I am available to submit a PR in case this is interesting. I looked into the code and have a first rough implementation that served my Python needs.

**Comment by boyter** [comment]
Nice. I agree that this should be by default similar to how grep and ripgrep work. 

Note that I want to refactor out the file walker into its own directory similar to how the string one currently is to allow it to be imported into other projects a little more easily.

I still need to think about how I want that to work, but I suspect it means I will change the channel it takes to return a custom struct for that thing itself. Ill move it out soon.

If we can then make changes to that code (which won't be used at first) that would be the best option. Ill mention the moment I have it moved out here.

**Comment by boyter** [comment]
File is here https://github.com/boyter/cs/blob/master/file/file.go

Have not moved anything over to use it yet, but thats were I would like it all to go.

**Comment by boyter** [comment]
Actually implemented now properly into the application so closing this down.
