### ISSUE TITLE
processor.findNearbySpace misreading spaces in multibyte codepoint strings

### ISSUE THREAD

**Issue by eL0ck** [boyter/cs#9]
Adding the following test reproduces the failure.

```diff
    8 var leftCases = map[string][]int{
    9         " aaaa":        {4, 0},  // {start position, expected result}
   10         "a aaa":        {4, 1},
   11         "aaaa ":        {4, 4},
   12         " 12345678901": {11, 11},
+  13         // No spaces, even the comma+space is a single codepoint
+  14         "“啊，公爵，热那": {24, 24},  // 24bytes long: Returns (pos, false)
   15 }
```

As you know, the problem is here:
```
276         if unicode.IsSpace(rune(res.Content[i])) {
```

The problem is that a rune is a unicode code-point which can be expressed in a number of ways on disk (utf8, 16 etc).  So simply casting to rune is not a stable operation.  

We'd have to know what type of encoding the byte slice is and use one of the appropriate decoders (e.g `utf8.DecodeRune`)

It seems to me that the only real option here is to split on a number of code-points including ASCII space.  As shown in this example, the code-point _comma+space_ would have to be included.  This strategy would mean iterating rune-by-rune rather than byte-by-byte.

What are your thoughts @boyter ?

**Comment by boyter** [comment]
That's one decent option. The other would be to bit twiddle to determine if the byte you are looking at is actually in the middle of a multi-byte string and then move around looking for a start and cut from there. Its not too hard to do so as the bits always indicate this, and it might be a useful function for other people.

I don't have any strong attachment to either so long as it easy to maintain.

**Comment by eL0ck** [comment]
So I have prototyped a 'bit twiddle' algo to skip bytes until we have the start of a code-point but it comes back to the question what do we want to consider 'Space'?

If its the same as `unicode.IsSpace` then we can write much clearer code that just looks for that (rather short) finite set.  I would love an excuse to fill the function with obscure bitwise ops but it feels a bit vain haha.

--- 

What are you happy to call 'Space' ?  Are these enough:
`'\t', '\n', '\v', '\f', '\r', ' ', U+0085 (NEL), U+00A0 (NBSP).`
https://golang.org/src/unicode/graphic.go?s=3997:4022#L116

`chinese_war_and_peace.txt` looks like the only matching character you'll find is `\n` Since it uses points like `，。`

```go
  7 func main(){
  8     //r := []rune("ABC€")
  9     r := []rune("，。")
 10     fmt.Println(r)        // [65292 12290]
 11     fmt.Printf("%U\n", r) // [U+FF0C U+3002]
 12 }
```

**Comment by boyter** [comment]
Yeah that seems fine from the point of a space.

The main thing about the issue here is where it goes looking for a space, cannot find one and then cuts in the middle of the multi-byte character. So long as that does not occur I am even happy just looking for ' ' since that's likely to be the most common case.

**Comment by boyter** [comment]
Closing down cos this is now resolved.
